[tools]
rust = { version = "1.95.0", components = "rustfmt,clippy" }
hk = "1.43.0"
pkl = "0.31.1"
taplo = "0.10.0"
actionlint = "1.7.12"
zizmor = "1.24.1"
typos = "1.45.1"
"aqua:EmbarkStudios/cargo-deny" = "0.19.4"
"cargo:cargo-deb" = "=3.6.3"
